// <auto-generated />
using System;
using Infrastructure.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240514060011_m1.0.4")]
    partial class m104
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Aggregates.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ModalityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModalityId");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Concourse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("OpeningTime")
                        .HasColumnType("time");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Concourses", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.ConcourseRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("ConcourseRules", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Modality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RegisterOfficeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RegisterOfficeId");

                    b.ToTable("Modalities", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.RegisterOffice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConcourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ConcourseId")
                        .IsUnique();

                    b.ToTable("RegisterOffices", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.TicketOffice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConcourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ConcourseId")
                        .IsUnique();

                    b.ToTable("TicketOffices", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Organizations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f7fa932-2d47-4f63-b82a-b73a2d8352ce"),
                            CreationDate = new DateTimeOffset(new DateTime(2024, 5, 14, 6, 0, 11, 35, DateTimeKind.Unspecified).AddTicks(881), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Default Organization"
                        });
                });

            modelBuilder.Entity("Domain.Aggregates.Category", b =>
                {
                    b.HasOne("Domain.Aggregates.Modality", "Modality")
                        .WithMany("Categories")
                        .HasForeignKey("ModalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modality");
                });

            modelBuilder.Entity("Domain.Aggregates.Concourse", b =>
                {
                    b.HasOne("Domain.Entities.Organization", "Organization")
                        .WithMany("Concourses")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Domain.Aggregates.ConcourseRule", b =>
                {
                    b.HasOne("Domain.Aggregates.Category", null)
                        .WithMany("ConcourseRules")
                        .HasForeignKey("CategoryId");
                });

            modelBuilder.Entity("Domain.Aggregates.Modality", b =>
                {
                    b.HasOne("Domain.Aggregates.RegisterOffice", null)
                        .WithMany("Modalities")
                        .HasForeignKey("RegisterOfficeId");
                });

            modelBuilder.Entity("Domain.Aggregates.RegisterOffice", b =>
                {
                    b.HasOne("Domain.Aggregates.Concourse", "Concourse")
                        .WithOne("RegisterOffice")
                        .HasForeignKey("Domain.Aggregates.RegisterOffice", "ConcourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concourse");
                });

            modelBuilder.Entity("Domain.Aggregates.TicketOffice", b =>
                {
                    b.HasOne("Domain.Aggregates.Concourse", "Concourse")
                        .WithOne("TicketOffice")
                        .HasForeignKey("Domain.Aggregates.TicketOffice", "ConcourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concourse");
                });

            modelBuilder.Entity("Domain.Aggregates.Category", b =>
                {
                    b.Navigation("ConcourseRules");
                });

            modelBuilder.Entity("Domain.Aggregates.Concourse", b =>
                {
                    b.Navigation("RegisterOffice");

                    b.Navigation("TicketOffice");
                });

            modelBuilder.Entity("Domain.Aggregates.Modality", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("Domain.Aggregates.RegisterOffice", b =>
                {
                    b.Navigation("Modalities");
                });

            modelBuilder.Entity("Domain.Entities.Organization", b =>
                {
                    b.Navigation("Concourses");
                });
#pragma warning restore 612, 618
        }
    }
}
